#!/bin/bash
cd $OPENSHIFT_REPO_DIR

export MAVEN_OPTS="-Xms384m -Xmx412m"
export M2_HOME=${OPENSHIFT_DATA_DIR}maven
export M2=${OPENSHIFT_DATA_DIR}maven/bin
export JAVA_HOME=${OPENSHIFT_DATA_DIR}java
export PATH=${JAVA_HOME}/bin:${M2}:$PATH

mvn package -s .openshift/settings.xml -DskipTests=true
