#!/bin/bash

export JAVA_HOME=${OPENSHIFT_DATA_DIR}java
export PATH=${JAVA_HOME}/bin:$PATH

echo JAVA_HOME: $JAVA_HOME
echo PATH: $PATH

echo `java -version`

cd $OPENSHIFT_REPO_DIR
nohup java -jar target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &