#!/bin/bash

export JAVA_HOME=${OPENSHIFT_DATA_DIR}java
export PATH=${JAVA_HOME}/bin:$PATH

cd $OPENSHIFT_REPO_DIR
nohup java -Xms384m -Xmx512m -jar -Dspring.profiles.active=openshift target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &
