#!/bin/bash

echo JAVA_HOME: $JAVA_HOME
echo PATH: $PATH

echo `java -version`

nohup java -jar ${OPENSHIFT_REPO_DIR}webapps/ROOT.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &